name: Tag Release Pipeline

on:
  push:
    branches:
      - main  # mainブランチにPush（マージ含む）されたら実行

jobs:
  tag-check:
    runs-on: self-hosted
    # Approval Gate（承認ゲート） リポジトリをPublicにする必要があります。
    # environment: production

    steps:
      # GitHub からソースコードを取得
      - name: Checkout source
        uses: actions/checkout@v4
        # 最新の 1 コミットだけを取得（パケット節約）
        with:
          fetch-depth: 1

      # ブランチ名と日時（ログ出力）
      - name: Show branch and deployment id
        run: |
          echo "Branch name = ${{ github.ref_name }}"
          echo "Time = $(date +'%Y-%m-%d %H:%M')"

      # SSH Agent 起動
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # known_hosts 登録（SSH 初回接続の接続確認を自動回避）
      - name: Add known hosts
        run: ssh-keyscan -H ${{ vars.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      # 実行ユーザーの表示
      - name: Check Runtime Environment
        run: |
          echo "=== Runtime User ==="
          whoami
          echo "=== Working Directory ==="
          pwd
          echo "=== Groups ==="
          groups

      - name: Run All Monitoring Tasks
        run: |
          cd ansible
          ansible-playbook -i hosts get_spec.yml
          ansible-playbook -i hosts security_check.yml
          ansible-playbook -i hosts patch_check.yml

      # GitHub Actions にレポートを表示
      - name: Show report in GitHub Actions
        run: |   
          echo "### Security & Patch Scan Results" >> $GITHUB_STEP_SUMMARY
          cat docs/security_report.txt >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          cat docs/patch_report.txt >> $GITHUB_STEP_SUMMARY

      # レポート内に WARNING という文字があれば、GitHubのログに警告を出す
      - name: Alert if vulnerability found
        run: |
          if grep -q "WARNING" docs/security_report.txt; then
            echo "::warning title=Security Alert::Unexpected port 80 is OPEN!"
          fi

      - name: Commit and Push reports
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # docs配下の全ファイルを対象にする
          git add docs/*.txt
          
          if ! git diff --cached --exit-code --quiet; then
            git commit -m "docs: auto-update server reports [skip ci]"
            git push
          else
            echo "No changes in reports. Skipping commit."
          fi

      # GitHub の画面で、最新のレポート群をダウンロードできるようにする
      - name: Upload All Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-full-reports
          path: docs/*.txt
          retention-days: 5
